name: Fetch and Decode Geo Files

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 5'  # 每周五午夜运行
  workflow_dispatch:  # 允许手动触发

jobs:
  fetch-and-decode-geo-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19.2

    - name: Install v2dat
      run: |
        go install github.com/urlesistiana/v2dat@latest

    - name: Install Aliyun CLI
      run: |
        wget https://aliyuncli.alicdn.com/aliyun-cli-linux-latest-amd64.tgz?spm=5176.8466032.console-base_help.1.683c14509cD8ib -O aliyun-cli.tgz
        tar -xzf aliyun-cli.tgz
        sudo cp aliyun /usr/local/bin
        echo 'export PATH=$PATH:/usr/local/bin' >> ~/.bash_profile
        source ~/.bash_profile

    - name: Fetch geosite.dat and geoip.dat
      run: |
        curl -LJO https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat
        curl -LJO https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat

    - name: Create output directory
      run: |
        mkdir -p dat

    - name: Unpack geoip.dat
      run: |
        v2dat unpack geoip -o dat -f "private" geoip.dat
        v2dat unpack geoip -o dat -f "cn" geoip.dat

    - name: Unpack geosite.dat
      run: |
        v2dat unpack geosite -o dat -f "cn" geosite.dat
        v2dat unpack geosite -o dat -f "gfw" geosite.dat
        v2dat unpack geosite -o dat -f "category-ads-all" geosite.dat
        v2dat unpack geosite -o dat -f "geolocation-!cn" geosite.dat

    - name: Move decoded files to root directory
      run: |
        mv dat/* .

    - name: Upload files to Aliyun OSS
      env:
        ALIYUN_ACCESS_KEY_ID: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
        ALIYUN_ACCESS_KEY_SECRET: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
        ALIYUN_OSS_BUCKET: ${{ secrets.ALIYUN_OSS_BUCKET }}
        ALIYUN_OSS_ENDPOINT: ${{ secrets.ALIYUN_OSS_ENDPOINT }}
      run: |
        aliyun oss cp geoip.dat oss://${{ secrets.ALIYUN_OSS_BUCKET }}/geoip.dat
        aliyun oss cp geoip_cn.txt oss://${{ secrets.ALIYUN_OSS_BUCKET }}/geoip_cn.txt
        aliyun oss cp geoip_private.txt oss://${{ secrets.ALIYUN_OSS_BUCKET }}/geoip_private.txt
        aliyun oss cp geosite.dat oss://${{ secrets.ALIYUN_OSS_BUCKET }}/geosite.dat
        aliyun oss cp geosite_category-ads-all.txt oss://${{ secrets.ALIYUN_OSS_BUCKET }}/geosite_category-ads-all.txt
        aliyun oss cp geosite_cn.txt oss://${{ secrets.ALIYUN_OSS_BUCKET }}/geosite_cn.txt
        aliyun oss cp geosite_geolocation-!cn.txt oss://${{ secrets.ALIYUN_OSS_BUCKET }}/geosite_geolocation-!cn.txt
        aliyun oss cp geosite_gfw.txt oss://${{ secrets.ALIYUN_OSS_BUCKET }}/geosite_gfw.txt
