name: Fetch and Decode Geo Files

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 5'  # 每周五午夜运行
  workflow_dispatch:  # 允许手动触发

jobs:
  fetch-and-decode-geo-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19.2

    - name: Install v2dat
      run: |
        go install github.com/urlesistiana/v2dat@latest

    - name: Fetch geosite.dat and geoip.dat
      run: |
        curl -LJO https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat
        curl -LJO https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat

    - name: Create output directory
      run: |
        mkdir -p dat

    - name: Unpack geoip.dat
      run: |
        v2dat unpack geoip -o dat -f "private" geoip.dat
        v2dat unpack geoip -o dat -f "cn" geoip.dat

    - name: Unpack geosite.dat
      run: |
        v2dat unpack geosite -o dat -f "cn" geosite.dat
        v2dat unpack geosite -o dat -f "gfw" geosite.dat
        v2dat unpack geosite -o dat -f "category-ads-all" geosite.dat
        v2dat unpack geosite -o dat -f "geolocation-!cn" geosite.dat

    - name: Move decoded files to root directory
      run: |
        mv dat/* .

    - name: Install Aliyun OSS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install aliyun-python-sdk-core-v3 aliyun-python-sdk-oss2

    - name: Upload files to Aliyun OSS
      env:
        ALIYUN_ACCESS_KEY_ID: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
        ALIYUN_ACCESS_KEY_SECRET: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
        ALIYUN_OSS_BUCKET: ${{ secrets.ALIYUN_OSS_BUCKET }}
        ALIYUN_OSS_ENDPOINT: ${{ secrets.ALIYUN_OSS_ENDPOINT }}
      run: |
        python3 -c "
        import oss2
        auth = oss2.Auth('${ALIYUN_ACCESS_KEY_ID}', '${ALIYUN_ACCESS_KEY_SECRET}')
        bucket = oss2.Bucket(auth, '${ALIYUN_OSS_ENDPOINT}', '${ALIYUN_OSS_BUCKET}')
        for file in ['geoip.dat', 'geoip_cn.txt', 'geoip_private.txt', 'geosite.dat', 'geosite_category-ads-all.txt', 'geosite_cn.txt', 'geosite_geolocation-!cn.txt', 'geosite_gfw.txt
