name: Fetch and Decode Geo Files

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 5'  # 每周五午夜运行
  workflow_dispatch:  # 允许手动触发

jobs:
  fetch-and-decode-geo-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19.2

    - name: Install v2dat
      run: |
        go install github.com/urlesistiana/v2dat@latest

    - name: Install qshell
      run: |
        wget https://github.com/qiniu/qshell/releases/download/v2.15.0/qshell-v2.15.0-linux-amd64.tar.gz
        tar -xzf qshell-v2.15.0-linux-amd64.tar.gz
        sudo mv qshell /usr/local/bin/
        chmod +x /usr/local/bin/qshell
        echo 'export PATH=$PATH:/usr/local/bin' >> ~/.bashrc
        source ~/.bashrc

    - name: Configure qshell
      env:
        QINIU_ACCESS_KEY: ${{ secrets.QINIU_ACCESS_KEY }}
        QINIU_SECRET_KEY: ${{ secrets.QINIU_SECRET_KEY }}
      run: |
        qshell account $QINIU_ACCESS_KEY $QINIU_SECRET_KEY

    - name: Fetch geosite.dat and geoip.dat
      run: |
        curl -LJO https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat
        curl -LJO https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat

    - name: Create output directory
      run: |
        mkdir -p dat

    - name: Unpack geoip.dat
      run: |
        v2dat unpack geoip -o dat -f "private" geoip.dat
        v2dat unpack geoip -o dat -f "cn" geoip.dat

    - name: Unpack geosite.dat
      run: |
        v2dat unpack geosite -o dat -f "cn" geosite.dat
        v2dat unpack geosite -o dat -f "gfw" geosite.dat
        v2dat unpack geosite -o dat -f "category-ads-all" geosite.dat
        v2dat unpack geosite -o dat -f "geolocation-!cn" geosite.dat

    - name: Move decoded files to root directory
      run: |
        mv dat/* .

    - name: Upload files to Qiniu Cloud
      env:
        QINIU_BUCKET: ${{ secrets.QINIU_BUCKET }}
      run: |
        qshell rput $QINIU_BUCKET mosdns/geoip.dat geoip.dat
        qshell rput $QINIU_BUCKET mosdns/geoip_cn.txt geoip_cn.txt
        qshell rput $QINIU_BUCKET mosdns/geoip_private.txt geoip_private.txt
        qshell rput $QINIU_BUCKET mosdns/geosite.dat geosite.dat
        qshell rput $QINIU_BUCKET mosdns/geosite_category-ads-all.txt geosite_category-ads-all.txt
        qshell rput $QINIU_BUCKET mosdns/geosite_cn.txt geosite_cn.txt
        qshell rput $QINIU_BUCKET mosdns/geosite_geolocation-!cn.txt geosite_geolocation-!cn.txt
        qshell rput $QINIU_BUCKET mosdns/geosite_gfw.txt geosite_gfw.txt
